### ISSUE TITLE
Notification not displayed

### ISSUE THREAD

**Issue by pun-ky** [dorkbox/Notify#11]
```
java.lang.NegativeArraySizeException
	at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.awt.GraphicsConfiguration.createCompatibleImage(GraphicsConfiguration.java:150)
	at java.awt.GraphicsConfiguration.createCompatibleImage(GraphicsConfiguration.java:178)
	at sun.awt.image.SunVolatileImage.getBackupImage(SunVolatileImage.java:250)
	at sun.awt.image.VolatileSurfaceManager.getBackupSurface(VolatileSurfaceManager.java:265)
	at sun.awt.image.VolatileSurfaceManager.initialize(VolatileSurfaceManager.java:124)
	at sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:92)
	at sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:102)
	at sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:113)
	at sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:107)
	at sun.awt.windows.WComponentPeer.createVolatileImage(WComponentPeer.java:785)
	at java.awt.Component.createVolatileImage(Component.java:3622)
	at java.awt.Component$BltBufferStrategy.createBackBuffers(Component.java:4349)
	at java.awt.Component$BltBufferStrategy.revalidate(Component.java:4460)
	at java.awt.Component$BltBufferStrategy.revalidate(Component.java:4445)
	at java.awt.Component$BltBufferStrategy.getDrawGraphics(Component.java:4365)
	at dorkbox.util.swing.ActiveRenderLoop.run(ActiveRenderLoop.java:82)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "AWT-ActiveRender" java.lang.NullPointerException
	at java.awt.Component$BltBufferStrategy.contentsLost(Component.java:4493)
	at dorkbox.util.swing.ActiveRenderLoop.run(ActiveRenderLoop.java:93)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pun-ky** [comment]
I have a hunch that it is somehow connected with fact that notification is being displayed by process running long time in the background (Gradle Daemon). 

See: https://github.com/Cognifide/gradle-aem-plugin/blob/master/src/main/kotlin/com/cognifide/gradle/aem/api/AemNotifier.kt#L35

Any ideas to prevent that error triggering?

**Comment by dorkbox** [comment]
I've seen that error a few times -- but was unable to track down exactly why. I'll look into it a bit more.

Can you tell me more about the system this happened on?

**Comment by dorkbox** [comment]
Once my build system is working again, I will push an update that fixes this issue.

**Comment by dorkbox** [comment]
By update, I mean a release. The current code, as-is, has this issue fixed. (It is rendering components differently, so this specific error should not happen again)
