### ISSUE TITLE
Found a few issues on Ubuntu 18.04

### ISSUE THREAD

**Issue by brandon3055** [dorkbox/Notify#15]
Just tried using this on Ubuntu 18.04 and found a few issues i thought you should know about.

- position and setScreen are completely broken. No matter what i do the notification is displayed in the top left of my left most monitor.
- hideAfter does not seem to work. It just stays open until clicked.
- shake does not work.
- And finally when i click a notification i get a null pointer exception

```
Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
	at dorkbox.notify.LookAndFeel.removePopupFromMap(LookAndFeel.java:421)
	at dorkbox.notify.LookAndFeel.updatePositionsPre(LookAndFeel.java:506)
	at dorkbox.notify.LookAndFeel.close(LookAndFeel.java:208)
	at dorkbox.notify.AsDesktop$1.run(AsDesktop.java:146)
	at dorkbox.util.SwingUtil.invokeLater(SwingUtil.java:329)
	at dorkbox.notify.AsDesktop.close(AsDesktop.java:141)
	at dorkbox.notify.LookAndFeel.onClick(LookAndFeel.java:150)
	at dorkbox.notify.AsDesktop.onClick(AsDesktop.java:95)
```

I stepped through that code and found that 'allLooks' is null 

```java
    private static
    boolean removePopupFromMap(final LookAndFeel sourceLook) {
        boolean showFromTop = isShowFromTop(sourceLook);
        boolean popupsAreEmpty;

        synchronized (popups) {
            popupsAreEmpty = popups.isEmpty();
            final PopupList allLooks = popups.get(sourceLook.idAndPosition); //This returns null

            // there are two loops because it is necessary to cancel + remove all tweens BEFORE adding new ones.
            boolean adjustPopupPosition = false;
            for (Iterator<LookAndFeel> iterator = allLooks.iterator(); iterator.hasNext(); ) {
```

I would also like to suggest the addition of Pos.TOP_CENTER so you can show the notification in the same place as default gnome notifications.

**Comment by dorkbox** [comment]
Fixed and added TOP, thanks!
