### ISSUE TITLE
Class not found on adopt JDK 9

### ISSUE THREAD

**Issue by pun-ky** [dorkbox/Notify#16]
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class sun.awt.CGraphicsEnvironment
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:292)
        at java.desktop/java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:104)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
        at java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
        at dorkbox.util.ImageUtil.resizeImage(ImageUtil.java:108)
        at dorkbox.notify.Notify.image(Notify.java:245)

```

```
➜   java -version
openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)

```

**Comment by dorkbox** [comment]
Thanks for the bug report!

**Comment by dorkbox** [comment]
This has been fixed.
